import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Beer,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  CircleDashed,
  Coffee,
  CreditCard,
  Dices,
  Dog,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Music,
  Package,
  Palette,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  home: Home,
  building: Building2,
  hammer: Hammer,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  utensils: Utensils,
  coffee: Coffee,
  "shopping-cart": ShoppingCart,
  beer: Beer,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  train: TrainFront,
  plane: Plane,
  umbrella: Umbrella,
  ticket: Ticket,
  film: Film,
  tv: Tv,
  music: Music,
  gamepad: Gamepad2,
  dices: Dices,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  package: Package,
  gift: Gift,
  repeat: Repeat,
  smartphone: Smartphone,
  laptop: Laptop,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  scissors: Scissors,
  sparkles: Sparkles,
  landmark: Landmark,
  receipt: Receipt,
  "credit-card": CreditCard,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  video: Video,
  palette: Palette,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  baby: Baby,
  dog: Dog,
  wallet: Wallet,
  "arrow-left-right": ArrowLeftRight,
  "circle-dashed": CircleDashed,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function CategoryIcon({ name, className, color }: { name?: string | null; className?: string; color?: string }) {
  const Icon = (name && CATEGORY_ICONS[name]) || null;
  if (!Icon) return null;
  return <Icon className={className} style={color ? { color } : undefined} strokeWidth={1.75} />;
}
